import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter, withComponentInputBinding, withInMemoryScrolling } from '@angular/router';
import { provideAnimations } from '@angular/platform-browser/animations';
import { provideHttpClient } from '@angular/common/http';
import { provideCharts, withDefaultRegisterables } from 'ng2-charts';
import {
  provideLucideIcons,
  LucideUsers,
  LucideStethoscope,
  LucideCalendar,
  LucideCalendarPlus,
  LucideStar,
  LucideHeart,
  LucideBell,
  LucideCheck,
  LucideCheckCircle,
  LucideAlertCircle,
  LucideAlertTriangle,
  LucideXCircle,
  LucideClock,
  LucideArrowRight,
  LucideSparkles,
  LucideShield,
  LucideLock,
  LucideMail,
  LucideFileText,
  LucideActivity,
  LucideBarChart3,
  LucideLayoutDashboard,
  LucideSettings,
  LucideUser,
  LucideLogOut,
  LucideX,
  LucideMenu,
  LucideChevronRight,
  LucideBarChart2,
  LucideShieldCheck,
  LucideFileSpreadsheet,
  LucideImage,
  LucideDownload,
  LucideCheckCheck,
  LucideSearch,
  LucidePlus,
  LucideFolderOpen,
  LucideChevronDown,
  LucideCalendarDays,
  LucideBone,
  LucideBaby,
  LucideSmile,
  LucideScanFace,
  LucideHeartPulse,
  LucideBan,
  LucideEye,
  LucideClipboardCheck,
  LucideClipboardList,
} from '@lucide/angular';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes, withComponentInputBinding(), withInMemoryScrolling({ scrollPositionRestoration: 'top' })),
    provideHttpClient(),
    provideAnimations(),
    provideCharts(withDefaultRegisterables()),
    provideLucideIcons(
      LucideUsers,
      LucideStethoscope,
      LucideCalendar,
      LucideCalendarPlus,
      LucideStar,
      LucideHeart,
      LucideBell,
      LucideCheck,
      LucideCheckCircle,
      LucideAlertCircle,
      LucideAlertTriangle,
      LucideXCircle,
      LucideClock,
      LucideArrowRight,
      LucideSparkles,
      LucideShield,
      LucideLock,
      LucideMail,
      LucideFileText,
      LucideActivity,
      LucideBarChart2,
      LucideBarChart3,
      LucideLayoutDashboard,
      LucideSettings,
      LucideUser,
      LucideLogOut,
      LucideX,
      LucideMenu,
      LucideChevronRight,
      LucideShieldCheck,
      LucideFileSpreadsheet,
      LucideImage,
      LucideDownload,
      LucideCheckCheck,
      LucideSearch,
      LucidePlus,
      LucideFolderOpen,
      LucideChevronDown,
      LucideCalendarDays,
      LucideBone,
      LucideBaby,
      LucideSmile,
      LucideScanFace,
      LucideHeartPulse,
      LucideBan,
      LucideEye,
      LucideClipboardCheck,
      LucideClipboardList,
    ),
  ],
};
